# Generated by Django 6.1.1 on 2026-10-05 12:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Se usa en el link: #catalogo/mates', unique=True, verbose_name='identificador')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, verbose_name='descripción')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden en que aparece en la página.')),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='identificador')),
                ('codigo', models.CharField(blank=True, help_text='Código de la lista de precios. Vacío si cada talle tiene el suyo.', max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]+$', 'El código solo puede tener números.')], verbose_name='código')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('precio', models.PositiveIntegerField(blank=True, help_text='En pesos. Vacío = a consultar.', null=True)),
                ('titulo_variantes', models.CharField(default='Talle', help_text='Lo que elige el cliente: Talle, Tamaño, Material…', max_length=30, verbose_name='título de las variantes')),
                ('destacado', models.BooleanField(default=False)),
                ('disponible', models.BooleanField(default=True, help_text='Si se desmarca, se muestra como Sin stock.')),
                ('publicado', models.BooleanField(default=True, help_text='Si se desmarca, no aparece en la página.')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='catalogo.categoria', verbose_name='categoría')),
            ],
            options={
                'ordering': ['categoria__orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.ImageField(upload_to='productos/')),
                ('orden', models.PositiveIntegerField(default=0, help_text='La de menor número es la principal.')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'imagen',
                'verbose_name_plural': 'imágenes',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Variante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej.: 42, XL, Alpaca', max_length=40)),
                ('codigo', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]+$', 'El código solo puede tener números.')], verbose_name='código')),
                ('precio', models.PositiveIntegerField(blank=True, help_text='Vacío = usa el precio del producto.', null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='catalogo.producto')),
            ],
            options={
                'ordering': ['orden', 'id'],
                'constraints': [models.UniqueConstraint(fields=('producto', 'nombre'), name='variante_unica_por_producto')],
            },
        ),
    ]
