# Generated by Django 6.1.1 on 2026-10-05 12:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp', models.CharField(help_text='Formato internacional sin espacios: 549 + característica + número. Ej.: 5492474468603', max_length=20, validators=[django.core.validators.RegexValidator('^[0-9]+$', 'El código solo puede tener números.')])),
                ('pauta_monto_minimo', models.PositiveIntegerField(default=200000, help_text='El descuento se aplica a compras mayores a este monto, en pesos.', verbose_name='monto mínimo de la pauta mayorista')),
                ('pauta_porcentaje', models.PositiveSmallIntegerField(default=15, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='porcentaje de descuento')),
            ],
            options={
                'verbose_name': 'configuración',
                'verbose_name_plural': 'configuración',
            },
        ),
    ]
