-- =========================================================
-- El Ceibo: catálogo real (lista de precios de julio)
--
-- Reemplaza TODO el contenido de la base por este catálogo:
-- borra productos y categorías existentes y carga los de la lista.
-- Se puede volver a ejecutar las veces que haga falta.
--
-- Requiere 01_esquema.sql actualizado o 04_codigos_y_talles.sql.
-- =========================================================

BEGIN;

DELETE FROM productos;   -- borra también sus variantes e imágenes
DELETE FROM categorias;

INSERT INTO categorias (id, nombre, descripcion, orden) VALUES
  ('mates', 'Mates', 'Mates imperiales, camioneros, torpedos y criollos.', 1),
  ('canastas', 'Canastas', 'Canastas materas de cuero y sintéticas, y portamates para el auto.', 2),
  ('bombillas', 'Bombillas', 'Bombillas pico de loro de acero y alpaca.', 3),
  ('yerberas', 'Yerberas', 'Juegos de latas para yerba y azúcar.', 4),
  ('bombachas', 'Bombachas', 'Bombachas de campo de grafa, de vestir y de corderoy.', 5),
  ('abrigos', 'Abrigos', 'Chalecos, camperas, suéteres, bufandas y corraleras.', 6),
  ('remeras-y-camisas', 'Remeras y camisas', 'Chombas, camisas y blusas.', 7),
  ('ponchos', 'Ponchos', 'Ponchos livianos, pesados y de niño.', 8),
  ('calzado', 'Calzado', 'Alpargatas, botas de cuero y medias.', 9),
  ('boinas-y-sombreros', 'Boinas y sombreros', 'Boinas de hilo y de paño, gorras vascas y sombreros.', 10),
  ('corbatines-y-panuelos', 'Corbatines y pañuelos', 'Corbatines, pañuelos y pasapañuelos.', 11),
  ('cintos-y-rastras', 'Cintos, rastras y tiradores', 'Cintos de cuero, rastras, tiradores y frentes de rastra.', 12);

-- Productos unificados (portamate, bombilla, bombachas, chaleco matelasé,
-- boina de hilo, tirador y frente de rastra) no tienen código propio:
-- cada variante lleva el código de la lista.
INSERT INTO productos (id, codigo, categoria_id, nombre, precio, titulo_variantes) VALUES
  ('mate-imperial-de-acero-bronce', '001', 'mates', 'Mate imperial de acero/bronce', 26000, 'Opción'),
  ('mate-imperial-de-alpaca', '002', 'mates', 'Mate imperial de alpaca', 30000, 'Opción'),
  ('mate-imperial-premium', '003', 'mates', 'Mate imperial premium', 35000, 'Opción'),
  ('mate-imperial-premium-argentina', '004', 'mates', 'Mate imperial premium Argentina', 35000, 'Opción'),
  ('mate-imperial-premium-de-algarrobo', '005', 'mates', 'Mate imperial premium de algarrobo', 35000, 'Opción'),
  ('mate-imperial-de-algarrobo-con-bombilla', '006', 'mates', 'Mate imperial de algarrobo con bombilla', 19000, 'Opción'),
  ('mate-camionero-de-algarrobo-con-bombilla', '007', 'mates', 'Mate camionero de algarrobo con bombilla', 17000, 'Opción'),
  ('mate-camionero', '008', 'mates', 'Mate camionero', 24000, 'Opción'),
  ('mate-torpedo', '009', 'mates', 'Mate torpedo', 24000, 'Opción'),
  ('mate-criollo-patas-de-alambre', '010', 'mates', 'Mate criollo patas de alambre', 15000, 'Opción'),
  ('mate-imperial-de-pvc', '011', 'mates', 'Mate imperial de PVC', 15000, 'Opción'),
  ('mate-de-acero', '012', 'mates', 'Mate de acero', 11000, 'Opción'),
  
  ('canasta-de-cuero-vaqueta', '013', 'canastas', 'Canasta de cuero vaqueta', 32000, 'Opción'),
  ('canasta-de-cuero-crudo', '014', 'canastas', 'Canasta de cuero crudo', 50000, 'Opción'),
  ('canasta-sintetica-con-manija-rigida', '015', 'canastas', 'Canasta sintética con manija rígida', 15000, 'Opción'),
  ('canasta-sintetica-alta', '016', 'canastas', 'Canasta sintética alta', 16000, 'Opción'),
  ('canasta-sintetica-simil-carpincho', '017', 'canastas', 'Canasta sintética símil carpincho', 20000, 'Opción'),
  ('portamate-para-auto', NULL, 'canastas', 'Portamate para auto', 7500, 'Material'),
  
  ('bombilla-pico-de-loro', NULL, 'bombillas', 'Bombilla pico de loro', 8000, 'Material'),
  
  ('latas-x2', '023', 'yerberas', 'Latas (x2)', 8000, 'Opción'),
  ('latas-grabadas-x2', '024', 'yerberas', 'Latas grabadas (x2)', 10000, 'Opción'),
  ('latas-simil-carpincho-x2', '025', 'yerberas', 'Latas símil carpincho (x2)', 12000, 'Opción'),
  ('chau-latas-x2', '026', 'yerberas', 'Chau latas (x2)', 8000, 'Opción'),
  
  ('bombacha-de-grafa', NULL, 'bombachas', 'Bombacha de grafa', 25000, 'Talle'),
  ('bombacha-de-vestir-mil-rayas-sarga', NULL, 'bombachas', 'Bombacha de vestir mil rayas/sarga', 28000, 'Talle'),
  ('bombacha-de-corderoy', '033', 'bombachas', 'Bombacha de corderoy', 48000, 'Talle'),
  
  ('chaleco-pampa', '034', 'abrigos', 'Chaleco pampa', 30000, 'Talle'),
  ('chaleco-pampa-con-botones', '035', 'abrigos', 'Chaleco pampa con botones', 30000, 'Talle'),
  ('campera-pampa', '036', 'abrigos', 'Campera pampa', 32000, 'Talle'),
  ('sueter-pampa', '037', 'abrigos', 'Suéter pampa', 35000, 'Talle'),
  ('chaleco-matelase', NULL, 'abrigos', 'Chaleco matelasé', 35000, 'Talle'),
  ('bufanda-pampa', '040', 'abrigos', 'Bufanda pampa', 14000, 'Opción'),
  ('bufandon', '041', 'abrigos', 'Bufandón', 40000, 'Opción'),
  ('corralera-de-mujer', '042', 'abrigos', 'Corralera de mujer', 75000, 'Talle'),
  ('chomba-pampa', '043', 'remeras-y-camisas', 'Chomba pampa', 25000, 'Talle'),
  ('camisa-cuello-mao', '044', 'remeras-y-camisas', 'Camisa cuello mao', 20000, 'Opción'),
  ('camisa-de-mujer', '045', 'remeras-y-camisas', 'Camisa de mujer', 20000, 'Talle'),
  ('blusa-de-broderie', '046', 'remeras-y-camisas', 'Blusa de broderie', 25000, 'Opción'),
  ('poncho-liviano', '047', 'ponchos', 'Poncho liviano', 45000, 'Opción'),
  ('poncho-pesado', '048', 'ponchos', 'Poncho pesado', 90000, 'Opción'),
  ('poncho-pampa-reversible', '049', 'ponchos', 'Poncho pampa reversible', 95000, 'Opción'),
  ('poncho-de-nino', '050', 'ponchos', 'Poncho de niño', 30000, 'Opción'),
  ('alpargata-confortable', '051', 'calzado', 'Alpargata confortable', 15000, 'Talle'),
  ('alpargata-confortable-con-suela-de-goma', '052', 'calzado', 'Alpargata confortable con suela de goma', 18000, 'Talle'),
  ('alpargata-cruda-economica', '053', 'calzado', 'Alpargata cruda económica', 9000, 'Talle'),
  ('alpargata-de-nino', '054', 'calzado', 'Alpargata de niño', 7000, 'Talle'),
  ('botas-de-cuero', '055', 'calzado', 'Botas de cuero', 180000, 'Talle'),
  ('medias-finas', '056', 'calzado', 'Medias finas', 3500, 'Opción'),
  ('boina-de-hilo-economica-vuelo-32', '057', 'boinas-y-sombreros', 'Boina de hilo económica, vuelo 32', 12000, 'Opción'),
  ('boina-de-hilo', NULL, 'boinas-y-sombreros', 'Boina de hilo', 15000, 'Vuelo'),
  ('boina-de-pano-economica-vuelo-32', '060', 'boinas-y-sombreros', 'Boina de paño económica, vuelo 32', 25000, 'Opción'),
  ('boina-de-pano-ftl-vuelo-32', '061', 'boinas-y-sombreros', 'Boina de paño FTL, vuelo 32', 35000, 'Opción'),
  ('boina-de-pano-grueso', '062', 'boinas-y-sombreros', 'Boina de paño grueso', 46000, 'Opción'),
  ('gorra-vasca-de-pano', '063', 'boinas-y-sombreros', 'Gorra vasca de paño', 14000, 'Opción'),
  ('gorra-vasca-de-cuerina', '064', 'boinas-y-sombreros', 'Gorra vasca de cuerina', 15000, 'Opción'),
  ('sombrero-de-pano-ala-ancha', '065', 'boinas-y-sombreros', 'Sombrero de paño ala ancha', 45000, 'Opción'),
  ('sombrero-de-rafia', '066', 'boinas-y-sombreros', 'Sombrero de rafia', 38000, 'Opción'),
  ('sombrero-de-rafia-de-papel', '067', 'boinas-y-sombreros', 'Sombrero de rafia de papel', 38000, 'Opción'),
  ('corbatin', '068', 'corbatines-y-panuelos', 'Corbatín', 7000, 'Opción'),
  ('panuelo-80-x-80', '069', 'corbatines-y-panuelos', 'Pañuelo 80 x 80', 12000, 'Opción'),
  ('panuelo-de-baile-celeste-y-blanco', '070', 'corbatines-y-panuelos', 'Pañuelo de baile celeste y blanco', 4500, 'Opción'),
  ('pasapanuelo', '071', 'corbatines-y-panuelos', 'Pasapañuelo', 8000, 'Opción'),
  ('cinto-de-cuero-con-hebilla-pampa', '072', 'cintos-y-rastras', 'Cinto de cuero con hebilla pampa', 15000, 'Opción'),
  ('cinto-de-cuero-con-yunta', '073', 'cintos-y-rastras', 'Cinto de cuero con yunta', 15000, 'Opción'),
  ('cinto-de-cuero-con-hebilla-de-mujer', '074', 'cintos-y-rastras', 'Cinto de cuero con hebilla de mujer', 15000, 'Opción'),
  ('cinto-de-cuero-crudo-con-yunta', '075', 'cintos-y-rastras', 'Cinto de cuero crudo con yunta', 18000, 'Opción'),
  ('cinto-de-cuero-crudo-con-hebilla-de-mujer', '076', 'cintos-y-rastras', 'Cinto de cuero crudo con hebilla de mujer', 18000, 'Opción'),
  ('rastrin-de-cuero-crudo', '077', 'cintos-y-rastras', 'Rastrín de cuero crudo', 22000, 'Opción'),
  ('cinto-de-cuero-de-nino', '078', 'cintos-y-rastras', 'Cinto de cuero de niño', 13000, 'Opción'),
  ('cinto-de-cuero-crudo-de-nino', '079', 'cintos-y-rastras', 'Cinto de cuero crudo de niño', 16000, 'Opción'),
  ('yunta-engarzada', '080', 'cintos-y-rastras', 'Yunta engarzada', 12000, 'Opción'),
  ('rastra-simil-carpincho-de-nino', '081', 'cintos-y-rastras', 'Rastra símil carpincho de niño', 24000, 'Opción'),
  ('rastra-simil-carpincho-con-hebilla-simple', '082', 'cintos-y-rastras', 'Rastra símil carpincho con hebilla simple', 28000, 'Opción'),
  ('rastra-simil-carpincho-con-hebilla-doble', '083', 'cintos-y-rastras', 'Rastra símil carpincho con hebilla doble', 30000, 'Opción'),
  ('rastra-de-cuero-vaqueta-completa', '084', 'cintos-y-rastras', 'Rastra de cuero vaqueta completa', 45000, 'Opción'),
  ('rastra-de-cuero-negro-completa', '085', 'cintos-y-rastras', 'Rastra de cuero negro completa', 50000, 'Opción'),
  ('rastra-de-cuero-crudo-completa', '086', 'cintos-y-rastras', 'Rastra de cuero crudo completa', 50000, 'Opción'),
  ('tirador-de-cuero', NULL, 'cintos-y-rastras', 'Tirador de cuero', 25000, 'Tamaño'),
  ('tirador-elastizado-de-carpincho', '089', 'cintos-y-rastras', 'Tirador elastizado de carpincho', 45000, 'Opción'),
  ('tirador-elastizado-de-cuero', '090', 'cintos-y-rastras', 'Tirador elastizado de cuero', 43000, 'Opción'),
  ('frente-de-rastra', NULL, 'cintos-y-rastras', 'Frente de rastra', 20000, 'Tamaño');

-- precio NULL = usa el precio del producto
INSERT INTO variantes (producto_id, nombre, codigo, precio, orden) VALUES
  ('portamate-para-auto', 'Sintético', '018', NULL, 1),
  ('portamate-para-auto', 'Cuero', '019', 16000, 2),
  ('bombilla-pico-de-loro', 'Acero', '020', NULL, 1),
  ('bombilla-pico-de-loro', 'Alpaca', '021', 16000, 2),
  ('bombilla-pico-de-loro', 'Alpaca premium', '022', 27000, 3),
  ('bombacha-de-grafa', '00', '028', NULL, 1),
  ('bombacha-de-grafa', '0', '028', NULL, 2),
  ('bombacha-de-grafa', '2', '028', NULL, 3),
  ('bombacha-de-grafa', '4', '028', NULL, 4),
  ('bombacha-de-grafa', '6', '028', NULL, 5),
  ('bombacha-de-grafa', '8', '028', NULL, 6),
  ('bombacha-de-grafa', '10', '028', NULL, 7),
  ('bombacha-de-grafa', '12', '028', NULL, 8),
  ('bombacha-de-grafa', '14', '027', 28000, 9),
  ('bombacha-de-grafa', '16', '027', 28000, 10),
  ('bombacha-de-grafa', '18', '027', 28000, 11),
  ('bombacha-de-grafa', '20', '027', 28000, 12),
  ('bombacha-de-grafa', '22', '027', 28000, 13),
  ('bombacha-de-grafa', '24', '027', 28000, 14),
  ('bombacha-de-grafa', '26', '027', 28000, 15),
  ('bombacha-de-grafa', '28', '027', 28000, 16),
  ('bombacha-de-grafa', '30', '027', 28000, 17),
  ('bombacha-de-grafa', '32', '027', 28000, 18),
  ('bombacha-de-grafa', '34', '027', 28000, 19),
  ('bombacha-de-grafa', '36', '027', 28000, 20),
  ('bombacha-de-grafa', '38', '027', 28000, 21),
  ('bombacha-de-grafa', '40', '027', 28000, 22),
  ('bombacha-de-grafa', '42', '027', 28000, 23),
  ('bombacha-de-grafa', '44', '027', 28000, 24),
  ('bombacha-de-grafa', '46', '027', 28000, 25),
  ('bombacha-de-grafa', '48', '027', 28000, 26),
  ('bombacha-de-grafa', '50', '027', 28000, 27),
  ('bombacha-de-grafa', '52', '027', 28000, 28),
  ('bombacha-de-grafa', '54', '029', 32000, 29),
  ('bombacha-de-grafa', '56', '029', 32000, 30),
  ('bombacha-de-grafa', '58', '029', 32000, 31),
  ('bombacha-de-grafa', '60', '029', 32000, 32),
  ('bombacha-de-grafa', '62', '029', 32000, 33),
  ('bombacha-de-vestir-mil-rayas-sarga', '00', '031', NULL, 1),
  ('bombacha-de-vestir-mil-rayas-sarga', '0', '031', NULL, 2),
  ('bombacha-de-vestir-mil-rayas-sarga', '2', '031', NULL, 3),
  ('bombacha-de-vestir-mil-rayas-sarga', '4', '031', NULL, 4),
  ('bombacha-de-vestir-mil-rayas-sarga', '6', '031', NULL, 5),
  ('bombacha-de-vestir-mil-rayas-sarga', '8', '031', NULL, 6),
  ('bombacha-de-vestir-mil-rayas-sarga', '10', '031', NULL, 7),
  ('bombacha-de-vestir-mil-rayas-sarga', '12', '031', NULL, 8),
  ('bombacha-de-vestir-mil-rayas-sarga', '14', '030', 32000, 9),
  ('bombacha-de-vestir-mil-rayas-sarga', '16', '030', 32000, 10),
  ('bombacha-de-vestir-mil-rayas-sarga', '18', '030', 32000, 11),
  ('bombacha-de-vestir-mil-rayas-sarga', '20', '030', 32000, 12),
  ('bombacha-de-vestir-mil-rayas-sarga', '22', '030', 32000, 13),
  ('bombacha-de-vestir-mil-rayas-sarga', '24', '030', 32000, 14),
  ('bombacha-de-vestir-mil-rayas-sarga', '26', '030', 32000, 15),
  ('bombacha-de-vestir-mil-rayas-sarga', '28', '030', 32000, 16),
  ('bombacha-de-vestir-mil-rayas-sarga', '30', '030', 32000, 17),
  ('bombacha-de-vestir-mil-rayas-sarga', '32', '030', 32000, 18),
  ('bombacha-de-vestir-mil-rayas-sarga', '34', '030', 32000, 19),
  ('bombacha-de-vestir-mil-rayas-sarga', '36', '030', 32000, 20),
  ('bombacha-de-vestir-mil-rayas-sarga', '38', '030', 32000, 21),
  ('bombacha-de-vestir-mil-rayas-sarga', '40', '030', 32000, 22),
  ('bombacha-de-vestir-mil-rayas-sarga', '42', '030', 32000, 23),
  ('bombacha-de-vestir-mil-rayas-sarga', '44', '030', 32000, 24),
  ('bombacha-de-vestir-mil-rayas-sarga', '46', '030', 32000, 25),
  ('bombacha-de-vestir-mil-rayas-sarga', '48', '030', 32000, 26),
  ('bombacha-de-vestir-mil-rayas-sarga', '50', '030', 32000, 27),
  ('bombacha-de-vestir-mil-rayas-sarga', '52', '030', 32000, 28),
  ('bombacha-de-vestir-mil-rayas-sarga', '54', '032', 34000, 29),
  ('bombacha-de-vestir-mil-rayas-sarga', '56', '032', 34000, 30),
  ('bombacha-de-vestir-mil-rayas-sarga', '58', '032', 34000, 31),
  ('bombacha-de-vestir-mil-rayas-sarga', '60', '032', 34000, 32),
  ('bombacha-de-corderoy', '38', NULL, NULL, 1),
  ('bombacha-de-corderoy', '40', NULL, NULL, 2),
  ('bombacha-de-corderoy', '42', NULL, NULL, 3),
  ('bombacha-de-corderoy', '44', NULL, NULL, 4),
  ('bombacha-de-corderoy', '46', NULL, NULL, 5),
  ('bombacha-de-corderoy', '48', NULL, NULL, 6),
  ('bombacha-de-corderoy', '50', NULL, NULL, 7),
  ('bombacha-de-corderoy', '52', NULL, NULL, 8),
  ('bombacha-de-corderoy', '54', NULL, NULL, 9),
  ('chaleco-pampa', 'S', NULL, NULL, 1),
  ('chaleco-pampa', 'M', NULL, NULL, 2),
  ('chaleco-pampa', 'L', NULL, NULL, 3),
  ('chaleco-pampa', 'XL', NULL, NULL, 4),
  ('chaleco-pampa', 'XXL', NULL, NULL, 5),
  ('chaleco-pampa-con-botones', 'S', NULL, NULL, 1),
  ('chaleco-pampa-con-botones', 'M', NULL, NULL, 2),
  ('chaleco-pampa-con-botones', 'L', NULL, NULL, 3),
  ('chaleco-pampa-con-botones', 'XL', NULL, NULL, 4),
  ('chaleco-pampa-con-botones', 'XXL', NULL, NULL, 5),
  ('campera-pampa', 'S', NULL, NULL, 1),
  ('campera-pampa', 'M', NULL, NULL, 2),
  ('campera-pampa', 'L', NULL, NULL, 3),
  ('campera-pampa', 'XL', NULL, NULL, 4),
  ('campera-pampa', 'XXL', NULL, NULL, 5),
  ('sueter-pampa', '1', NULL, NULL, 1),
  ('sueter-pampa', '2', NULL, NULL, 2),
  ('sueter-pampa', '3', NULL, NULL, 3),
  ('chaleco-matelase', '4', '039', NULL, 1),
  ('chaleco-matelase', '6', '039', NULL, 2),
  ('chaleco-matelase', '8', '039', NULL, 3),
  ('chaleco-matelase', '10', '039', NULL, 4),
  ('chaleco-matelase', '12', '039', NULL, 5),
  ('chaleco-matelase', '14', '039', NULL, 6),
  ('chaleco-matelase', '16', '039', NULL, 7),
  ('chaleco-matelase', 'S', '038', 48000, 8),
  ('chaleco-matelase', 'M', '038', 48000, 9),
  ('chaleco-matelase', 'L', '038', 48000, 10),
  ('chaleco-matelase', 'XL', '038', 48000, 11),
  ('chaleco-matelase', 'XXL', '038', 48000, 12),
  ('corralera-de-mujer', 'S', NULL, NULL, 1),
  ('corralera-de-mujer', 'M', NULL, NULL, 2),
  ('corralera-de-mujer', 'L', NULL, NULL, 3),
  ('corralera-de-mujer', 'XL', NULL, NULL, 4),
  ('corralera-de-mujer', 'XXL', NULL, NULL, 5),
  ('chomba-pampa', 'S', NULL, NULL, 1),
  ('chomba-pampa', 'M', NULL, NULL, 2),
  ('chomba-pampa', 'L', NULL, NULL, 3),
  ('chomba-pampa', 'XL', NULL, NULL, 4),
  ('chomba-pampa', 'XXL', NULL, NULL, 5),
  ('camisa-de-mujer', '1', NULL, NULL, 1),
  ('camisa-de-mujer', '2', NULL, NULL, 2),
  ('camisa-de-mujer', '3', NULL, NULL, 3),
  ('alpargata-confortable', '34', NULL, NULL, 1),
  ('alpargata-confortable', '35', NULL, NULL, 2),
  ('alpargata-confortable', '36', NULL, NULL, 3),
  ('alpargata-confortable', '37', NULL, NULL, 4),
  ('alpargata-confortable', '38', NULL, NULL, 5),
  ('alpargata-confortable', '39', NULL, NULL, 6),
  ('alpargata-confortable', '40', NULL, NULL, 7),
  ('alpargata-confortable', '41', NULL, NULL, 8),
  ('alpargata-confortable', '42', NULL, NULL, 9),
  ('alpargata-confortable', '43', NULL, NULL, 10),
  ('alpargata-confortable', '44', NULL, NULL, 11),
  ('alpargata-confortable', '45', NULL, NULL, 12),
  ('alpargata-confortable', '46', NULL, NULL, 13),
  ('alpargata-confortable-con-suela-de-goma', '34', NULL, NULL, 1),
  ('alpargata-confortable-con-suela-de-goma', '35', NULL, NULL, 2),
  ('alpargata-confortable-con-suela-de-goma', '36', NULL, NULL, 3),
  ('alpargata-confortable-con-suela-de-goma', '37', NULL, NULL, 4),
  ('alpargata-confortable-con-suela-de-goma', '38', NULL, NULL, 5),
  ('alpargata-confortable-con-suela-de-goma', '39', NULL, NULL, 6),
  ('alpargata-confortable-con-suela-de-goma', '40', NULL, NULL, 7),
  ('alpargata-confortable-con-suela-de-goma', '41', NULL, NULL, 8),
  ('alpargata-confortable-con-suela-de-goma', '42', NULL, NULL, 9),
  ('alpargata-confortable-con-suela-de-goma', '43', NULL, NULL, 10),
  ('alpargata-cruda-economica', '34', NULL, NULL, 1),
  ('alpargata-cruda-economica', '35', NULL, NULL, 2),
  ('alpargata-cruda-economica', '36', NULL, NULL, 3),
  ('alpargata-cruda-economica', '37', NULL, NULL, 4),
  ('alpargata-cruda-economica', '38', NULL, NULL, 5),
  ('alpargata-cruda-economica', '39', NULL, NULL, 6),
  ('alpargata-cruda-economica', '40', NULL, NULL, 7),
  ('alpargata-cruda-economica', '41', NULL, NULL, 8),
  ('alpargata-cruda-economica', '42', NULL, NULL, 9),
  ('alpargata-cruda-economica', '43', NULL, NULL, 10),
  ('alpargata-cruda-economica', '44', NULL, NULL, 11),
  ('alpargata-cruda-economica', '45', NULL, NULL, 12),
  ('alpargata-de-nino', '23', NULL, NULL, 1),
  ('alpargata-de-nino', '24', NULL, NULL, 2),
  ('alpargata-de-nino', '25', NULL, NULL, 3),
  ('alpargata-de-nino', '26', NULL, NULL, 4),
  ('alpargata-de-nino', '27', NULL, NULL, 5),
  ('alpargata-de-nino', '28', NULL, NULL, 6),
  ('alpargata-de-nino', '29', NULL, NULL, 7),
  ('alpargata-de-nino', '30', NULL, NULL, 8),
  ('alpargata-de-nino', '31', NULL, NULL, 9),
  ('alpargata-de-nino', '32', NULL, NULL, 10),
  ('alpargata-de-nino', '33', NULL, NULL, 11),
  ('botas-de-cuero', '41', NULL, NULL, 1),
  ('botas-de-cuero', '42', NULL, NULL, 2),
  ('botas-de-cuero', '43', NULL, NULL, 3),
  ('botas-de-cuero', '44', NULL, NULL, 4),
  ('botas-de-cuero', '45', NULL, NULL, 5),
  ('boina-de-hilo', '27', '058', NULL, 1),
  ('boina-de-hilo', '32', '058', NULL, 2),
  ('boina-de-hilo', '35', '059', 18000, 3),
  ('tirador-de-cuero', 'Chico', '087', NULL, 1),
  ('tirador-de-cuero', 'Grande', '088', 30000, 2),
  ('frente-de-rastra', 'Chico', '092', NULL, 1),
  ('frente-de-rastra', 'Grande', '091', 30000, 2);

COMMIT;


SELECT codigo, id, nombre FROM vista_productos WHERE fotos = 0;