
   INSERT INTO imagenes (producto_id, ruta, orden) VALUES
   ('mate-imperial-de-acero-bronce', 'img/productos/mate-imperial-de-acero-bronce.jpg', 1),
   ('mate-imperial-de-alpaca', 'img/productos/mate-imperial-de-alpaca.jpg', 1),
   ('mate-imperial-premium', 'img/productos/mate-imperial-premium.jpg', 1),
   ('mate-imperial-premium', 'img/productos/mate-imperial-premium-2.jpg', 2),
   ('mate-imperial-de-algarrobo-con-bombilla', 'img/productos/mate-imperial-de-algarrobo-con-bombilla.jpg', 1),
   ('mate-camionero-de-algarrobo-con-bombilla', 'img/productos/mate-camionero-de-algarrobo-con-bombilla.jpg', 1),
   ('mate-camionero-de-algarrobo-con-bombilla', 'img/productos/mate-camionero-de-algarrobo-con-bombilla-2.jpg', 2),
   ('mate-camionero-de-algarrobo-con-bombilla', 'img/productos/mate-camionero-de-algarrobo-con-bombilla-3.jpg', 3),
   ('mate-camionero', 'img/productos/mate-camionero.jpg', 1),
   ('mate-camionero', 'img/productos/mate-camionero-2.jpg', 2),
   ('mate-imperial-premium-de-algarrobo', 'img/productos/mate-imperial-premium-de-algarrobo.jpg', 1),
   ('mate-imperial-premium-argentina', 'img/productos/mate-imperial-premium-argentina.jpg', 1),
   ('mate-torpedo', 'img/productos/mate-torpedo.jpg', 1),
   ('mate-torpedo', 'img/productos/mate-torpedo-2.jpg', 2),
   ('mate-torpedo', 'img/productos/mate-torpedo-3.jpg', 3),
   ('mate-imperial-de-pvc', 'img/productos/mate-imperial-de-pvc.jpg', 1),
   ('mate-imperial-de-pvc', 'img/productos/mate-imperial-de-pvc-2.jpg', 2),
   ('mate-criollo-patas-de-alambre', 'img/productos/mate-criollo-patas-de-alambre.jpg', 1),
   ('mate-de-acero', 'img/productos/mate-de-acero.jpg', 1),

   ('canasta-de-cuero-vaqueta', 'img/productos/canasta-de-cuero-vaqueta.jpg', 1),
   ('canasta-de-cuero-crudo', 'img/productos/canasta-de-cuero-crudo.jpg', 1),
   ('canasta-de-cuero-crudo', 'img/productos/canasta-de-cuero-crudo-2.jpg', 2),
   ('canasta-sintetica-con-manija-rigida', 'img/productos/canasta-sintetica-con-manija-rigida.jpg', 1),
   ('canasta-sintetica-alta', 'img/productos/canasta-sintetica-alta.jpg', 1),
   ('canasta-sintetica-simil-carpincho', 'img/productos/canasta-de-simil-carpincho.jpg', 1),

   ('bombilla-pico-de-loro-acero', 'img/productos/bombilla-acero.jpg', 1),
   ('bombilla-pico-de-loro-alpaca', 'img/productos/bombilla-alpaca.jpg', 1),
   ('bombilla-pico-de-loro-alpaca', 'img/productos/bombilla-ambas.jpg', 2),
   ('bombilla-pico-de-loro-con-aplique', 'img/productos/bombilla-aplique.jpg', 1),
   ('bombilla-pico-de-loro-con-aplique', 'img/productos/bombilla-ambas.jpg', 2),

   ('latas-x2', 'img/productos/latas.jpg', 1),
   ('latas-grabadas-x2', 'img/productos/latas-grabadas.jpg', 1),
   ('latas-simil-carpincho-x2', 'img/productos/latas-simil-carpincho.jpg', 1),
   ('chau-latas-x2', 'img/productos/chau-latas.jpg', 1),

   ('bombacha-de-grafa', 'img/productos/bombacha-de-grafa.jpg', 1),
   ('bombacha-de-grafa', 'img/productos/bombacha-de-grafa-2.jpg', 2),
   ('bombacha-de-corderoy', 'img/productos/bombacha-de-corderoy.jpg', 1),
   ('bombacha-de-corderoy', 'img/productos/bombacha-de-corderoy-2.jpg', 2),
   ('bombacha-de-vestir-mil-rayas-sarga', 'img/productos/bombacha-de-vestir.jpg', 1),

    
   ('chaleco-pampa', 'img/productos/chaleco-pampa.jpg', 1),
   ('chaleco-pampa', 'img/productos/chaleco-pampa-2.jpg', 1),
   ('chaleco-pampa-con-botones', 'img/productos/chaleco-pampa-con-botones.jpg',1),
   ('campera-pampa', 'img/productos/chaleco-pampa.jpg', 1),
   ('sueter-pampa', 'img/productos/sueter-pampa.jpg', 1),
   ('chaleco-matelase', 'img/productos/chaleco-matelase.jpg', 1),
   ('bufanda-pampa', 'img/productos/bufanda-pampa.jpg', 1),
   ('bufandon', 'img/productos/bufandon.jpg', 1),
   ('corralera-de-mujer', 'img/productos/corralera-de-mujer.jpg', 1),

   ('chomba-pampa', 'img/productos/chomba-pampa.jpg', 1),
   ('chomba-pampa', 'img/productos/chomba-pampa-2.jpg', 2),
   ('chomba-pampa', 'img/productos/chomba-pampa-3.jpg', 3),
   ('chomba-pampa', 'img/productos/chomba-pampa-4.jpg', 4),
   ('camisa-cuello-mao', 'img/productos/camisa-cuello-mao.jpg', 1),
   ('camisa-de-mujer', 'img/productos/camisa-de-mujer.jpg', 1),
   ('camisa-de-mujer', 'img/productos/camisa-de-mujer-2.jpg', 2),
   ('blusa-de-broderie', 'img/productos/blusa-de-broderie.jpg', 1),
   ('blusa-de-broderie', 'img/productos/blusa-de-broderie-2.jpg', 2),
   ('blusa-de-broderie', 'img/productos/blusa-de-broderie-3.jpg', 3),
   ('blusa-de-broderie', 'img/productos/blusa-de-broderie-4.jpg', 4),
   ('blusa-de-broderie', 'img/productos/blusa-de-broderie-5.jpg', 5),
   
   ('poncho-liviano', 'img/productos/poncho-liviano.jpg', 1),
   ('poncho-pesado', 'img/productos/poncho-pesado.jpg', 1),
   ('poncho-pampa-reversible', 'img/productos/poncho-pampa-reversible.jpg', 1),
   ('poncho-de-nino', 'img/productos/poncho-de-nino.jpg', 1),

   ('alpargata-confortable', 'img/productos/alpargata-confortable.jpg', 1),
   ('alpargata-confortable-con-suela-de-goma', 'img/productos/alpargata-confortable-con-suela-de-goma.jpg', 1),
   ('alpargata-de-nino', 'img/productos/alpargata-de-nino.jpg', 1),
   ('botas-de-cuero', 'img/productos/botas-de-cuero.jpg', 1),
   ('medias-finas', 'img/productos/medias-finas.jpg', 1),

   ('boina-de-hilo-economica-vuelo-32', 'img/productos/boinas-ambas.jpg', 1),
   ('boina-de-hilo', 'img/productos/boinas-ambas.jpg', 1),
   ('boina-de-pano-economica-vuelo-32', 'img/productos/boina-de-pano-economica-vuelo-32.jpg', 1),
   ('boina-de-pano-ftl-vuelo-32','img/productos/boina-de-pano-ftl-vuelo-32.jpg', 1),
   ('boina-de-pano-grueso', 'img/productos/boina-de-pano-grueso.jpg', 1),
   ('gorra-vasca-de-pano', 'img/productos/gorra-vasca-de-pano.jpg', 1),
   ('gorra-vasca-de-cuerina', 'img/productos/gorra-vasca-de-cuerina.jpg', 1),
   ('sombrero-de-pano-ala-ancha', 'img/productos/sombrero-de-pano-ala-ancha.jpg', 1),
   ('sombrero-de-rafia', 'img/productos/sombrero-de-rafia.jpg', 1),
   ('sombrero-de-rafia-de-papel', 'img/productos/sombrero-de-rafia-de-papel.jpg', 1),

   ('corbatin', 'img/productos/corbatin.jpg', 1),
   ('panuelo-80-x-80', 'img/productos/panuelo-80-x-80.jpg', 1),
   ('panuelo-de-baile-celeste-y-blanco', 'img/productos/panuelo-de-baile-celeste-y-blanco.jpg', 1),
   ('pasapanuelo', 'img/productos/pasapanuelo.jpg', 1),

   ('cinto-de-cuero-con-hebilla-pampa', 'img/productos/cinto-de-cuero-con-hebilla-pampa.jpg', 1),
   ('cinto-de-cuero-con-yunta', 'img/productos/cinto-de-cuero-crudo.jpg', 1),
   ('cinto-de-cuero-con-hebilla-de-mujer', 'img/productos/cinto-de-cuero-con-hebilla-de-mujer.jpg', 1),
   ('cinto-de-cuero-crudo-con-yunta', 'img/productos/cinto-de-cuero-crudo-con-yunta.jpg', 1),
   ('cinto-de-cuero-crudo-con-hebilla-de-mujer', 'img/productos/cinto-de-cuero-crudo-con-hebilla-de-mujer.jpg', 1),
     
   ('rastrin-de-cuero-crudo', 'img/productos/rastrin-de-cuero-crudo.jpg', 1),
   ('cinto-de-cuero-de-nino', 'img/productos/cinto-de-cuero-de-nino.jpg', 1),
   ('cinto-de-cuero-crudo-de-nino', 'img/productos/cinto-de-cuero-crudo-de-nino.jpg', 1),
   ('yunta-engarzada', 'img/productos/yunta-engarzada.jpg', 1),
   
   ('rastra-simil-carpincho-de-nino', 'img/productos/rastra-simil-carpincho-de-nino.jpg', 1),
   ('rastra-simil-carpincho-con-hebilla-simple', 'img/productos/rastra-simil-carpincho-con-hebilla-simple.jpg', 1),
   ('rastra-simil-carpincho-con-hebilla-doble', 'img/productos/rastra-simil-carpincho-con-hebilla-doble.jpg', 1),
   ('rastra-de-cuero-vaqueta-completa', 'img/productos/rastra-de-cuero-vaqueta-completa.jpg', 1),
   ('rastra-de-cuero-negro-completa', 'img/productos/rastra-de-cuero-negro-completa.jpg', 1),
   ('rastra-de-cuero-crudo-completa', 'img/productos/rastra-de-cuero-crudo-completa.jpg', 1),

   ('tirador-de-cuero', 'img/productos/tirador-de-cuero.jpg', 1),
   ('tirador-elastizado-de-carpincho', 'img/productos/tirador-elastizado-de-carpincho.jpg', 1),
   ('tirador-elastizado-de-cuero','img/productos/tirador-elastizado-de-cuero.jpg', 1),
   ('frente-de-rastra', 'img/productos/frente-de-rastra.jpg', 1)

   ON CONFLICT (producto_id, ruta) DO NOTHING;

   